-- Category data import
INSERT INTO category (id, name, description) VALUES
(1, 'Jersey', 'Jersey'),
(2, '5s Jersey', 'Fivesleeve'),
(3, 'Kids Jersey', 'Kids Jersey'),
(4, 'First Copy Jersey', 'FC Jersey'),
(5, 'Tshirt', 'Tshirt'),
(6, 'Dotknit Shorts - Embroidery', 'Dotknit Shorts - Embroidery'),
(7, 'Dotknit Shorts - Submiation', 'Dotknit Shorts - Submiation'),
(8, 'Dotknit Shorts - Plain', 'Dotknit Shorts - Plain'),
(9, 'PP Shorts - Plain', 'PP Shorts - Plain'),
(10, 'PP Shorts - Embroidery', 'PP Shorts - Embroidery'),
(11, 'FC Shorts', 'FC Shorts'),
(12, 'NS Shorts', 'NS Shorts'),
(13, 'Sleeve Less - D/N', 'Sleeve Less - D/N'),
(14, 'Sleeve Less - Saleena', 'Sleeve Less - Saleena'),
(15, 'Sleeve Less - Other', 'Sleeve Less - Other'),
(16, 'Sleeve Less - NS', 'Sleeve Less - NS'),
(17, 'Track Pants - Imp', 'Track Pants - Imp'),
(18, 'Track Pants - Normal', 'Track Pants - Normal'),
(19, 'Boot-Adult', 'Boot-Adult'),
(20, 'Boot-Kids', 'Boot-Kids'),
(21, 'Shorts-Kids', 'Shorts-Kids'),
(22, 'Boot-Imp', 'Boot-Imp'),
(23, 'Football', 'Football'),
(24, 'Cricket Ball', 'Cricket Ball'),
(25, 'Shuttle Bat', 'Shuttle Bat'),
(26, 'Shuttle Cock', 'Shuttle cock'),
(27, 'Foot Pad', 'Foot pad'),
(28, 'Foot sleeve', 'Foot sleeve'),
(29, 'Socks-Full', 'Socks-Full'),
(30, 'Socks-3/4', 'Socks-3/4'),
(31, 'Socks-Half', 'Socks-Half'),
(32, 'Socks-Ankle', 'Socks-Ankle'),
(33, 'Hand Sleeve', 'Hand Sleeve'),
(34, 'GK Glove', 'GK Glove'),
(35, 'Trophy', 'Trophy');

-- Reset the sequence to the next available ID
SELECT setval('category_id_seq', (SELECT MAX(id) FROM category));
