-- Category data import
INSERT INTO public.categories (id, name, description) VALUES
(1, 'Normal Sleeve Jersey', 'Jersey'),
(2, 'F/S Jersey', 'Full Sleeve'),
(3, 'Five Sleeve Jersey', '5/S'),
(4, 'Kids Jersey', 'Kids Jersey'),
(5, 'First Copy Jersey', 'FC Jersey'),
(6, 'Tshirt', 'Tshirt'),
(7, 'Dotknit Shorts - Embroidery', 'Dotknit Shorts - Embroidery'),
(8, 'Dotknit Shorts - Submiation', 'Dotknit Shorts - Submiation'),
(9, 'Dotknit Shorts - Plain', 'Dotknit Shorts - Plain'),
(10, 'PP Shorts - Plain', 'PP Shorts - Plain'),
(11, 'PP Shorts - Embroidery', 'PP Shorts - Embroidery'),
(12, 'FC Shorts', 'FC Shorts'),
(13, 'NS Shorts', 'NS Shorts'),
(14, 'Sleeve Less - D/N', 'Sleeve Less - D/N'),
(15, 'Sleeve Less - Saleena', 'Sleeve Less - Saleena'),
(16, 'Sleeve Less - Other', 'Sleeve Less - Other'),
(17, 'Sleeve Less - NS', 'Sleeve Less - NS'),
(18, 'Track Pants - Imp', 'Track Pants - Imp'),
(19, 'Track Pants - Normal', 'Track Pants - Normal'),
(20, 'Boot-Adult', 'Boot-Adult'),
(21, 'Boot-Kids', 'Boot-Kids'),
(22, 'Shorts-Kids', 'Shorts-Kids'),
(23, 'Boot-Imp', 'Boot-Imp'),
(24, 'Football', 'Football'),
(25, 'Cricket Ball', 'Cricket Ball'),
(26, 'Shuttle Bat', 'Shuttle Bat'),
(27, 'Shuttle Cock', 'Shuttle cock'),
(28, 'Foot Pad', 'Foot pad'),
(29, 'Foot sleeve', 'Foot sleeve'),
(30, 'Socks-Full', 'Socks-Full'),
(31, 'Socks-3/4', 'Socks-3/4'),
(32, 'Socks-Half', 'Socks-Half'),
(33, 'Socks-Ankle', 'Socks-Ankle'),
(34, 'Hand Sleeve', 'Hand Sleeve'),
(35, 'GK Glove', 'GK Glove'),
(36, 'Trophy', 'Trophy');
