INSERT INTO public.products
(id, name, description, unit_price, selling_price, is_active, can_listed, image_url, category_id, offer_id, discounted_price, offer_price, offer_name, created_date, updated_date, created_by, updated_by)
VALUES
-- Estimate No: 19806
(1, 'SHORTS ARSENAL WHITE', 'SHORTS ARSENAL WHITE', 120, 225, TRUE, TRUE, NULL, 8, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(2, 'TERSTEGAN FCB 25-26 GREEN', 'TERSTEGAN FCB 25-26 GREEN', 165, 275, TRUE, TRUE, NULL, 3, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(3, 'COURTOIS REAL 25-26 SKY BLUE GK', 'COURTOIS REAL 25-26 SKY BLUE GK', 165, 275, TRUE, TRUE, NULL, 3, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(4, 'NEYMAR SANTOS 3RD COLLAR', 'NEYMAR SANTOS 3RD COLLAR', 195, 325, TRUE, TRUE, NULL, 3, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(5, 'LAMINE YAMAL FCB BLACK', 'LAMINE YAMAL FCB BLACK', 165, 275, TRUE, TRUE, NULL, 3, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(6, 'ENDRICK REAL HOME 25-26', 'ENDRICK REAL HOME 25-26', 165, 275, TRUE, TRUE, NULL, 3, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(7, 'DE JONG FCB AWAY 25-26', 'DE JONG FCB AWAY 25-26', 165, 275, TRUE, TRUE, NULL, 3, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(8, 'DYBALA ROMA 25-26 3RD COLLAR', 'DYBALA ROMA 25-26 3RD COLLAR', 195, 325, TRUE, TRUE, NULL, 3, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(9, 'ODEGAARD ARSENAL 25-26 3RD COLLAR', 'ODEGAARD ARSENAL 25-26 3RD COLLAR', 195, 325, TRUE, TRUE, NULL, 3, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(10, 'WIRTZ LFC HOME 25-26', 'WIRTZ LFC HOME 25-26', 195, 325, TRUE, TRUE, NULL, 2, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(11, 'MESSI ARG 2010 AWAY', 'MESSI ARG 2010 AWAY', 195, 325, TRUE, TRUE, NULL, 2, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),

-- Estimate No: 19591
(12, 'GYOKERES ARSENAL HOME 25-26', 'GYOKERES ARSENAL HOME 25-26', 165, 275, TRUE, TRUE, NULL, 3, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(13, 'PALMER CHELSEA HOME 26-25', 'PALMER CHELSEA HOME 26-25', 165, 275, TRUE, TRUE, NULL, 3, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(14, 'KIMMICH BAYERN 25-26 3RD', 'KIMMICH BAYERN 25-26 3RD', 165, 275, TRUE, TRUE, NULL, 3, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(15, 'VIRGIL LFC AWAY 25-26', 'VIRGIL LFC AWAY 25-26', 165, 275, TRUE, TRUE, NULL, 3, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(16, 'DEMBELE PSG HOME 25-26', 'DEMBELE PSG HOME 25-26', 165, 275, TRUE, TRUE, NULL, 3, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(17, 'VALVERDE REAL 25-26 HOME', 'VALVERDE REAL 25-26 HOME', 165, 275, TRUE, TRUE, NULL, 3, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(18, 'AGUERO CITY HOME 1999-2000 COLLAR', 'AGUERO CITY HOME 1999-2000 COLLAR', 215, 350, TRUE, TRUE, NULL, 3, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(19, 'PIRLO ITALY AWAY 2016 COLLAR', 'PIRLO ITALY AWAY 2016 COLLAR', 215, 350, TRUE, TRUE, NULL, 3, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(20, 'BECKHAM UNITED HOME 1996 COLLAR', 'BECKHAM UNITED HOME 1996 COLLAR', 215, 350, TRUE, TRUE, NULL, 3, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(21, 'BECKENBAUER GERMANY B&W 1994 COLLAR', 'BECKENBAUER GERMANY B&W 1994 COLLAR', 215, 350, TRUE, TRUE, NULL, 3, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(22, 'SHORTS BVB BLACK DOT', 'SHORTS BVB BLACK DOT', 85, 175, TRUE, TRUE, NULL, 7, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(23, 'SHORTS FCB NAVY', 'SHORTS FCB NAVY', 85, 175, TRUE, TRUE, NULL, 7, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(24, 'SHORTS CITY WHITE', 'SHORTS CITY WHITE', 85, 175, TRUE, TRUE, NULL, 7, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(25, 'SHORTS AC MILAN WHITE', 'SHORTS AC MILAN WHITE', 85, 175, TRUE, TRUE, NULL, 7, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(26, 'SHORTS CITY BLACK', 'SHORTS CITY BLACK', 85, 175, TRUE, TRUE, NULL, 7, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system'),
(27, 'SHORTS REAL BLACK', 'SHORTS REAL BLACK', 85, 175, TRUE, TRUE, NULL, 7, NULL, NULL, NULL, NULL, NOW(), NOW(), 'system', 'system');
