INSERT INTO public.products
(id, name, description, unit_price, selling_price, is_active, can_listed, image_url, category_id,
 offer_id, discounted_price, offer_price, offer_name, created_date, updated_date, created_by, updated_by)
VALUES
-- 🟩 ANZA
(306, 'ANZA M22 BLUE', 'ANZA M22 FULL BLUE', 650, 1150, TRUE, TRUE, NULL, 20, NULL, 950, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(307, 'ANZA Bhasma WHITE', 'ANZA Bhasma FLEXBLE FULL WHITE', 500, 1000, TRUE, TRUE, NULL, 20, NULL, 800, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(308, 'ANZA M22 RED', 'ANZA M22 FULL RED', 650, 1150, TRUE, TRUE, NULL, 20, NULL, 950, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(315, 'ANZA ICONIC MIXED COLOUR', 'ANZA ICONIC MIXED COLOUR', 500, 1000, TRUE, TRUE, NULL, 20, NULL, 800, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(316, 'ANZA REVOLT BLUE', 'ANZA REVOLT BLUE', 490, 990, TRUE, TRUE, NULL, 20, NULL, 790, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(319, 'ANZA PYTHOGORUS BLUE', 'ANZA PYTHOGORUS BLUE', 900, 1400, TRUE, TRUE, NULL, 20, NULL, 1200, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(321, 'ANZA SWITCH BLUE', 'ANZA SWITCH BLUE', 1100, 1600, TRUE, TRUE, NULL, 20, NULL, 1400, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(323, 'ANZA OGRE PINK', 'ANZA OGRE PINK', 1300, 1800, TRUE, TRUE, NULL, 20, NULL, 1600, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(327, 'ANZA EXCEED BLUE MIXED', 'ANZA EXCEED BLUE MIXED', 720, 1220, TRUE, TRUE, NULL, 20, NULL, 1020, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(329, 'ANZA SHEILD WHITE', 'ANZA SHEILD WHITE', 800, 1300, TRUE, TRUE, NULL, 20, NULL, 1100, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(330, 'ANZA COPA RISE ORANGE', 'ANZA COPA RISE ORANGE', 625, 1125, TRUE, TRUE, NULL, 20, NULL, 925, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(332, 'ANZA NERVE PURPLE', 'ANZA NERVE PURPLE', 700, 1200, TRUE, TRUE, NULL, 20, NULL, 1000, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(335, 'ANZA ZOOMBA WHITE', 'ANZA ZOOMBA WHITE', 600, 1100, TRUE, TRUE, NULL, 20, NULL, 900, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(336, 'ANZA SURGE WHITE', 'ANZA SURGE WHITE', 700, 1200, TRUE, TRUE, NULL, 20, NULL, 1000, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),

-- 🟦 FELO
(309, 'FELO KING BLUE AND BLACK', 'FELO KING BLUE AND BLACK', 425, 925, TRUE, TRUE, NULL, 20, NULL, 725, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(310, 'FELO GENESIS WHITE AND GREEN', 'FELO GENESIS WHITE AND GREEN', 425, 925, TRUE, TRUE, NULL, 20, NULL, 725, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(311, 'FELO KING WHITE AND RED', 'FELO KING WHITE AND RED', 425, 925, TRUE, TRUE, NULL, 20, NULL, 725, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(314, 'FELO GENESIS WHITE AND BLACK', 'FELO GENESIS WHITE AND BLACK', 425, 925, TRUE, TRUE, NULL, 20, NULL, 725, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(317, 'FELO FOCUS WHITE AND BLACK', 'FELO FOCUS WHITE AND BLACK', 430, 930, TRUE, TRUE, NULL, 20, NULL, 730, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(318, 'FELO HAVOC WHITE AND BLACK', 'FELO HAVOC WHITE AND BLACK', 425, 925, TRUE, TRUE, NULL, 20, NULL, 725, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(320, 'FELO ZOOM WHITE BLUE', 'FELO ZOOM WHITE BLUE', 600, 1100, TRUE, TRUE, NULL, 20, NULL, 900, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(324, 'FELO SUPERFLY WHITE AND PINK', 'FELO SUPERFLY WHITE AND PINK', 500, 1000, TRUE, TRUE, NULL, 20, NULL, 800, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(333, 'FELO RAPTOR WHITE AND BLUE', 'FELO RAPTOR WHITE AND BLUE', 500, 1000, TRUE, TRUE, NULL, 20, NULL, 800, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(334, 'FELO SPARTA GREEN', 'FELO SPARTA GREEN', 500, 1000, TRUE, TRUE, NULL, 20, NULL, 800, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(338, 'FELO KING PLUS GOLDEN', 'FELO KING PLUS GOLDEN', 425, 925, TRUE, TRUE, NULL, 20, NULL, 725, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(339, 'FELO KING BLUE AND WHITE', 'FELO KING BLUE AND WHITE', 425, 925, TRUE, TRUE, NULL, 20, NULL, 725, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(340, 'FELO SIGNATURE WHITE AND RED', 'FELO SIGNATURE WHITE AND RED', 500, 1000, TRUE, TRUE, NULL, 20, NULL, 800, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(341, 'FELO SIGNATURE BLACK AND BLUE', 'FELO SIGNATURE BLACK AND BLUE', 500, 1000, TRUE, TRUE, NULL, 20, NULL, 800, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),

-- 🟥 SEGA
(322, 'SEGA IDEA PINK', 'SEGA IDEA PINK', 500, 1000, TRUE, TRUE, NULL, 20, NULL, 800, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(326, 'SEGA MICRA GREEN', 'SEGA MICRA GREEN', 450, 950, TRUE, TRUE, NULL, 20, NULL, 750, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(328, 'SEGA SPECTRA YELLOW', 'SEGA SPECTRA YELLOW', 450, 950, TRUE, TRUE, NULL, 20, NULL, 750, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(331, 'SEGA SPECTRA PRIMER RED', 'SEGA SPECTRA PRIMER RED', 450, 950, TRUE, TRUE, NULL, 20, NULL, 750, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(342, 'SEGA STAR IMPACT BLUE', 'SEGA STAR IMPACT BLUE', 450, 950, TRUE, TRUE, NULL, 20, NULL, 750, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(343, 'SEGA STAR IMPACT YELLOW', 'SEGA STAR IMPACT YELLOW', 450, 950, TRUE, TRUE, NULL, 20, NULL, 750, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),

-- 🟨 IONE
(312, 'IONE FALCON WHITE AND GREEN', 'IONE FALCON WHITE AND GREEN', 475, 975, TRUE, TRUE, NULL, 20, NULL, 775, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),
(337, 'IONE PUKS MEDORA ANKLE WHITE AND GREEN', 'IONE PUKS ANKLE WHITE AND GREEN', 900, 1400, TRUE, TRUE, NULL, 20, NULL, 1200, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),

-- 🟪 NIVIA
(313, 'NIVIA SAFARI FULL GREEN', 'NIVIA SAFARI FULL GREEN', 700, 1200, TRUE, TRUE, NULL, 20, NULL, 1000, NULL, NULL, NOW(), NOW(), 'admin', 'admin'),

-- 🟧 VECTORX
(325, 'VECTORX RIDER+ INDOR', 'VECTORX RIDER+ INDOR', 900, 1400, TRUE, TRUE, NULL, 20, NULL, 1200, NULL, NULL, NOW(), NOW(), 'admin', 'admin');
