"""add duplicate fields to products

Revision ID: 1bccfe71359d
Revises: 8ca9884e5698
Create Date: 2026-06-07 14:31:11.646645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bccfe71359d'
down_revision = '8ca9884e5698'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_duplicate', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('products', sa.Column('parent_product_id', sa.Integer(), sa.ForeignKey('products.id'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'parent_product_id')
    op.drop_column('products', 'is_duplicate')
    # ### end Alembic commands ###
