"""Add whatsapp and other links to Shop

Revision ID: 3ca337c806e3
Revises: f081df237bd5
Create Date: 2025-08-10 10:17:57.473133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca337c806e3'
down_revision = 'f081df237bd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('whatsapp_group_link', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('instagram_link', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('website_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'website_link')
    op.drop_column('shops', 'instagram_link')
    op.drop_column('shops', 'whatsapp_group_link')
    # ### end Alembic commands ###
