"""Initial migration with all tables

Revision ID: 627526f6db24
Revises: 
Create Date: 2025-07-28 18:02:10.640877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627526f6db24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_sizes_id'), 'product_sizes', ['id'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_category', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('quantity_available', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_id'), 'sale_items', ['id'], unique=False)
    op.drop_table('product_size_map')
    op.drop_table('sale_item')
    op.drop_table('attribute_values')
    op.alter_column('attributes', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_attributes_id'), 'attributes', ['id'], unique=False)
    op.create_index(op.f('ix_attributes_name'), 'attributes', ['name'], unique=False)
    op.drop_column('attributes', 'description')
    op.alter_column('categories', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.alter_column('delivery_types', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_delivery_types_id'), 'delivery_types', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_types_name'), 'delivery_types', ['name'], unique=False)
    op.alter_column('payment_types', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_payment_types_id'), 'payment_types', ['id'], unique=False)
    op.create_index(op.f('ix_payment_types_name'), 'payment_types', ['name'], unique=False)
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('products', 'unit_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'selling_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.alter_column('purchase_items', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('purchase_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchase_items', 'quantity_available',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchase_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchase_items', 'purchase_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('purchase_items', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_purchase_items_id'), 'purchase_items', ['id'], unique=False)
    op.add_column('purchases', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.alter_column('purchases', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('purchases', 'total_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchases', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_purchases_id'), 'purchases', ['id'], unique=False)
    op.create_foreign_key(None, 'purchases', 'shops', ['shop_id'], ['id'])
    op.add_column('sales', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.alter_column('sales', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sales', 'total_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_foreign_key(None, 'sales', 'shops', ['shop_id'], ['id'])
    op.add_column('shops', sa.Column('location', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('contact', sa.String(), nullable=True))
    op.alter_column('shops', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_shops_id'), 'shops', ['id'], unique=False)
    op.create_index(op.f('ix_shops_name'), 'shops', ['name'], unique=False)
    op.drop_column('shops', 'city')
    op.drop_column('shops', 'address_line1')
    op.drop_column('shops', 'zipcode')
    op.drop_column('shops', 'country')
    op.drop_column('shops', 'state')
    op.drop_column('shops', 'mobile_number')
    op.drop_column('shops', 'email')
    op.drop_column('shops', 'address_line2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('address_line2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('shops', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('shops', sa.Column('mobile_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('shops', sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('shops', sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('shops', sa.Column('zipcode', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('shops', sa.Column('address_line1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('shops', sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_shops_name'), table_name='shops')
    op.drop_index(op.f('ix_shops_id'), table_name='shops')
    op.alter_column('shops', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('shops', 'contact')
    op.drop_column('shops', 'location')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.alter_column('sales', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sales', 'total_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('sales', 'shop_id')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_index(op.f('ix_purchases_id'), table_name='purchases')
    op.alter_column('purchases', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('purchases', 'total_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchases', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('purchases', 'shop_id')
    op.drop_index(op.f('ix_purchase_items_id'), table_name='purchase_items')
    op.alter_column('purchase_items', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('purchase_items', 'purchase_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('purchase_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchase_items', 'quantity_available',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchase_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchase_items', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.alter_column('products', 'selling_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'unit_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_payment_types_name'), table_name='payment_types')
    op.drop_index(op.f('ix_payment_types_id'), table_name='payment_types')
    op.alter_column('payment_types', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_delivery_types_name'), table_name='delivery_types')
    op.drop_index(op.f('ix_delivery_types_id'), table_name='delivery_types')
    op.alter_column('delivery_types', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.alter_column('categories', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('attributes', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_attributes_name'), table_name='attributes')
    op.drop_index(op.f('ix_attributes_id'), table_name='attributes')
    op.alter_column('attributes', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('attribute_values',
    sa.Column('attribute_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('values', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name='fkkaq0fvnivyrmqu857uy04xgmm')
    )
    op.create_table('sale_item',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('product_category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_available', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sale_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name='fkdjr346l9a8kku0uao1jorl1nj'),
    sa.PrimaryKeyConstraint('id', name='sale_item_pkey')
    )
    op.create_table('product_size_map',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk56t8yxis6ux4p4gxovxd1jng5'),
    sa.PrimaryKeyConstraint('product_id', 'size', name='product_size_map_pkey')
    )
    op.drop_index(op.f('ix_sale_items_id'), table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_product_sizes_id'), table_name='product_sizes')
    op.drop_table('product_sizes')
    # ### end Alembic commands ###
