"""Add offer columns to products table

Revision ID: 8a3e5b00bb79
Revises: 841ad65b2256
Create Date: 2025-08-08 06:40:49.962675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3e5b00bb79'
down_revision = '841ad65b2256'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discounted_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('offer_price', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_products_offer_id_event_offers', 'event_offers', ['offer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_offer_id_event_offers', type_='foreignkey')
        batch_op.drop_column('offer_price')
        batch_op.drop_column('discounted_price')
        batch_op.drop_column('offer_id')

    # ### end Alembic commands ###
